version: "3.7"

services:
  serverdev_apache:
    build: 
      context: ./bin/apache
      dockerfile: Dockerfile
      args:
        developer_uid: ${APACHE_DEVELOPER_UID}
        developer_name: ${USER}
    container_name: serverdev_apache
    restart: 'on-failure'
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ~/.ssh:/home/${USER}/.ssh
      - ~/.gitconfig:/home/${USER}/.gitconfig
      - ${APACHE_DOCUMENT_ROOT}:/var/www/html
      - ${PHP_CONFIG_INI}:/usr/local/etc/php/php.ini
      - ${APACHE_CONFIG_DIR}/sites-enabled:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2
    environment:
      APACHE_RUN_USER: ${USER}
      APACHE_RUN_GROUP: ${USER}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
      TZ: ${TIME_ZONE}
    user: ${USER}
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    networks:
      - serverdev_network
  serverdev_mysql:
    build: ./bin/mysql
    container_name: serverdev_mysql
    restart: 'on-failure'
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
      - ${MYSQL_CONFIG_DIR}:/etc/mysql/conf.d
      - ${MYSQL_DATA_IMPORT}:/tmp/import
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TIME_ZONE}
    networks:
      - serverdev_network
  serverdev_pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: serverdev_pma
    ports:
      - "${PMA_PORT}:80"
    restart: 'on-failure'
    environment:
      PMA_HOST: serverdev_mysql
      PMA_PORT: ${MYSQL_PORT}
      PMA_VERBOSE: localhost
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT}
    networks:
     - serverdev_network

networks:
  serverdev_network:
    external: true
